map *  <Plug>(asterisk-z*)
map #  <Plug>(asterisk-z#)
map z*   <Plug>(asterisk-*)
map z#   <Plug>(asterisk-#)
map g*  <Plug>(asterisk-g*)
map g#  <Plug>(asterisk-g#)
map gz* <Plug>(asterisk-gz*)
map gz# <Plug>(asterisk-gz#)
