[character]      # The name of the module we are configuring is "character"
success_symbol = "[λ](bold blue)"
error_symbol = "[λ](bold red)"
vicmd_symbol = "[](bold green)"

[python]
symbol = " "

[golang]
symbol = " "

[aws]
disabled = true
