local M = {}

M.config = function()
  -- local dial = require "dial"
  -- vim.cmd [[
  --   nmap <C-a> <Plug>(dial-increment)
  --     nmap <C-x> <Plug>(dial-decrement)
  --     vmap <C-a> <Plug>(dial-increment)
  --     vmap <C-x> <Plug>(dial-decrement)
  --     vmap g<C-a> <Plug>(dial-increment-additional)
  --     vmap g<C-x> <Plug>(dial-decrement-additional)
  --   ]]

  -- dial.augends["custom#boolean"] = dial.common.enum_cyclic {
  --   name = "boolean",
  --   strlist = { "true", "false" },
  -- }
  -- table.insert(dial.config.searchlist.normal, "custom#boolean")

  -- -- For Languages which prefer True/False, e.g. python.
  -- dial.augends["custom#Boolean"] = dial.common.enum_cyclic {
  --   name = "Boolean",
  --   strlist = { "True", "False" },
  -- }
  -- table.insert(dial.config.searchlist.normal, "custom#Boolean")
end

-- M.config = function()
--   local augend = require("dial.augend")

--   require("dial.config").augends:register_group {
--     -- "number#decimal#fixed#zero",
--     -- "markup#markdown#header",
--     default = {
--       augend.integer.alias.decimal_int,
--       augend.integer.alias.hex,
--       augend.integer.alias.octal,
--       augend.integer.alias.binary,
--       augend.constant.alias.bool,
--       augend.semver.alias.semver,
--       augend.date.alias["%Y/%m/%d"],
--       augend.date.alias["%Y-%m-%d"],
--       augend.date.alias["%H:%M:%S"],
--       augend.date.alias["%H:%M"],
--       -- lowercase hex colour #1a1a1a
--       augend.hexcolor.new {
--         case = "lower"
--       },
--       -- uppercase hex colour #1A1A1A
--       -- augend.user.new{
--       -- find = require("dial.augend.common").find_pattern("%d+"),
--       -- add = function(text, addend, cursor)
--       -- local n = tonumber(text)
--       -- n = math.floor(n * (2 ^ addend))
--       -- text = tostring(n)
--       -- cursor = #text
--       -- return {text = text, cursor = cursor}
--       -- end
--       -- },
--       augend.constant.new {
--         elements = { "Foreground", "Background" },
--         word = true, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "foreground", "background" },
--         word = true, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "&&", "||" },
--         word = false, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "yes", "no" },
--         word = false, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "Yes", "No" },
--         word = false, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "True", "False" },
--         word = false, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE", "OFF" },
--         word = false, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "fatal", "error", "warn", "info", "debug", "trace" },
--         word = false, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "public", "protected", "private" },
--         word = false, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October",
--           "November", "December" },
--         word = false, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" },
--         word = false, cyclic = true,
--       },
--       augend.constant.new {
--         elements = { "FIX:", "FIXJC:", "FIXME:", "BUG:", "FIXIT:", "ISSUE:", "TODO:", "HACK:", "WARN:", "WARNING:",
--           "XXX:", "PERF:", "OPTIM:", "PERFORMANCE:", "OPTIMIZE:", "NOTE:", "INFO:", "TEST:", "OK:", "ISH:", "BAD:" },
--         word = false, cyclic = true,
--       },
--     },
--   }

-- end

return M
