abbr -a -U -- dj django-admin
abbr -a -U -- ga 'git add -A'
abbr -a -U -- gb 'git branch'
abbr -a -U -- gch 'git checkout'
abbr -a -U -- gcm 'git commit -m'
abbr -a -U -- gdel 'git branch -d'
abbr -a -U -- glog 'git log --oneline'
abbr -a -U -- gnew 'git checkout -b'
abbr -a -U -- gst 'git status'
abbr -a -U -- gtrack 'git checkout --track'
abbr -a -U -- guntrack 'git rm -r --cached'
abbr -a -U -- gwt 'git worktree'
abbr -a -U -- ipy ipython
abbr -a -U -- mang 'python manage.py'
abbr -a -U -- moon 'curl wttr.in/moon'
abbr -a -U -- pip 'python -m pip'
abbr -a -U -- pipi 'python -m pip install'
abbr -a -U -- rbmaster 'git rebase master'
abbr -a -U -- venv 'python -m venv'
abbr -a -U -- weather 'curl wttr.in'
abbr -a -U -- zg lazygit
